### PR TITLE
402 - Update footer to match library footer

### LINKED ISSUE #402: Footer update to match Libraries footer
Our footer should match [the library's footer](https://libraries.uc.edu).  

Right now, we're missing one link - "Bearcats Portal" which should be directly below "Catalyst".  
We need to update our copywrite date from 2023 to 2024.
Links should not be underlined in the main footer section, but links in the bottom, white section should be underlined.
Upon resizing to mobile view, footer should re-organize to mobile-friendly view rather than just narrowing.

The Twitter icon needs updated to the X icon, but that will require updating to font awesome version 6, where we are currently using version 5.  This will need to be addressed in a separate issue.  See https://github.com/FortAwesome/Font-Awesome/issues/19931

### PR DESCRIPTION
**Pull request by Janell-Huyck**
Fixes #402

Updates footer to more closely match the [UC Library footer](https://libraries.uc.edu/).

- Adds "Bearcat Portal" link
- Updates copywrite year to 2024
- Makes layout mobile-friendly and responsive
- Removes underlines from resources links to match the library site

### CODE REVIEW

**Comment by hortongn** [comment]
@haitzlm I'd like you to review this next week.

**Comment by haitzlm** [comment]
will do

Lisa Haitz

Developer
UC Libraries
________________________________

**Review by haitzlm — COMMENTED** [review]
The links on this are all correct. However, there  should be no underlines for an state of the footer links (a:active, a:visited, etc...)) . I see the lines on both local and deployed version.

**Comment by haitzlm** [comment]
See my comment re underlines on links

**Comment by Janell-Huyck** [comment]
I don't understand your comment, but I do see on the main website that the very bottom links, while underlined, become not-underlined on hover, and the main lines, while not-underlined, become underlined on hover.  Fixing this now.  If you meant something else please clarify.

**Review by haitzlm — APPROVED** [review]
This code is correct for underlines...which was the only issue I had.

**Pull request merged**
