### PR TITLE
Footer updates partial fix for 171

### PR DESCRIPTION
**Pull request by haitzlm**
refs #171

* Updated footer with correct links to match UC website
* Updated CSS so footer lines don't wrap
* Updated broken links in footer

### CODE REVIEW

**Review by Janell-Huyck — CHANGES_REQUESTED** [review]
Overall looks good.  A couple of small tweaks:

The "Jobs" link is different.  The correct link is: https://www.uc.edu/careers.html

The "News" and "Events Calendar" links on our site should end in ".html"

We need a link to "Free Speech" in the bottom section.  The link on the main page is broken (like their links to Non-Discrimination and Privacy) because the link lacks ".html" at the end.  The correct link is https://www.uc.edu/freespeech.html.

**Comment by hortongn** [comment]
@haitzlm reminder to follow up on this PR next week.

**Review by Janell-Huyck — APPROVED** [review]
fixed my requested changes with commit df4647f1079995af22d718e35047cd3a77d72524

**Comment by crowesn** [comment]
Looks good, merging.

**Pull request merged**
